import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
//import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-3xl'>Testing</main>

      <footer className='text-3xl'></footer>
    </div>
  );
};

export default Home;

//import type { ReactElement } from 'react'
//import Layout from '../components/layout'
//import NestedLayout from '../components/nested-layout'
//import type { NextPageWithLayout } from './_app'

//const Page: NextPageWithLayout = () => {
//  return <p>hello world</p>
//}

//Page.getLayout = function getLayout(page: ReactElement) {
//  return (
//    <Layout>
//      <NestedLayout>{page}</NestedLayout>
//    </Layout>
//  )
//}

//export default Page
