import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

//import type { ReactElement } from 'react'
//import Layout from '../components/layout'
//import NestedLayout from '../components/nested-layout'
//import type { NextPageWithLayout } from './_app'

//const Page: NextPageWithLayout = () => {
//  return <p>hello world</p>
//}

//Page.getLayout = function getLayout(page: ReactElement) {
//  return (
//    <Layout>
//      <NestedLayout>{page}</NestedLayout>
//    </Layout>
//  )
//}

//export default Page
